// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeMVC_DB_Identitty.Models;

#nullable disable

namespace PracticeMVC_DB_Identitty.Migrations
{
    [DbContext(typeof(PracticeMVCDBContext))]
    [Migration("20260407181017_InitialBusinessData")]
    partial class InitialBusinessData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticeMVC_DB_Identitty.Models.Courses", b =>
                {
                    b.Property<int>("Cour_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cour_Id"));

                    b.Property<string>("Cour_Cont")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cour_Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cour_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cour_price")
                        .HasColumnType("float");

                    b.HasKey("Cour_Id");

                    b.ToTable("Coursess");
                });

            modelBuilder.Entity("PracticeMVC_DB_Identitty.Models.Fees", b =>
                {
                    b.Property<int>("rec_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rec_Id"));

                    b.Property<int>("Studentstu_Id")
                        .HasColumnType("int");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("f_date")
                        .HasColumnType("date");

                    b.Property<int>("stu_Id")
                        .HasColumnType("int");

                    b.HasKey("rec_Id");

                    b.HasIndex("Studentstu_Id");

                    b.ToTable("Feess");
                });

            modelBuilder.Entity("PracticeMVC_DB_Identitty.Models.Student", b =>
                {
                    b.Property<int>("stu_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stu_Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("age")
                        .HasColumnType("date");

                    b.Property<string>("stu_Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stu_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stu_mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stu_Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PracticeMVC_DB_Identitty.Models.Fees", b =>
                {
                    b.HasOne("PracticeMVC_DB_Identitty.Models.Student", "Student")
                        .WithMany("Fees")
                        .HasForeignKey("Studentstu_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PracticeMVC_DB_Identitty.Models.Student", b =>
                {
                    b.HasOne("PracticeMVC_DB_Identitty.Models.Courses", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("PracticeMVC_DB_Identitty.Models.Courses", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("PracticeMVC_DB_Identitty.Models.Student", b =>
                {
                    b.Navigation("Fees");
                });
#pragma warning restore 612, 618
        }
    }
}
